"""Mensaje de la migración

Revision ID: 39291912508b
Revises: 406faccc3f06
Create Date: 2025-07-08 17:15:03.172684

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '39291912508b'
down_revision = '406faccc3f06'
branch_labels = None
depends_on = None


def upgrade():
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Caracteristica', schema=None) as batch_op:
        batch_op.add_column(sa.Column('eliminado', sa.Boolean(), nullable=True))

    with op.batch_alter_table('Caracteristica_Plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('eliminado', sa.Boolean(), nullable=True))

    with op.batch_alter_table('Caracteristica_Usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('eliminado', sa.Boolean(), nullable=True))

    #with op.batch_alter_table('Dispositivo', schema=None) as batch_op:
        #batch_op.add_column(sa.Column('cedula', sa.String(length=10), nullable=False))
        #batch_op.add_column(sa.Column('eliminado', sa.Boolean(), nullable=True))

    with op.batch_alter_table('Permiso', schema=None) as batch_op:
        #batch_op.add_column(sa.Column('eliminado', sa.Boolean(), nullable=True))
        batch_op.drop_constraint('Permiso_id_gestor_permiso_fkey', type_='foreignkey')
        batch_op.drop_constraint('Permiso_id_permiso_usuario_fkey', type_='foreignkey')
        batch_op.drop_column('id_permiso_usuario')
        batch_op.drop_column('id_gestor_permiso')

    with op.batch_alter_table('Permiso_usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_usuario', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('id_permiso', sa.Integer(), nullable=False))
        #batch_op.add_column(sa.Column('eliminado', sa.Boolean(), nullable=True))
        batch_op.create_foreign_key(None, 'Usuario', ['id_usuario'], ['id'])
        batch_op.create_foreign_key(None, 'Permiso', ['id_permiso'], ['id'])

    with op.batch_alter_table('Plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('eliminado', sa.Boolean(), nullable=True))

    with op.batch_alter_table('Punto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lng', sa.Float(), nullable=False))
        #batch_op.add_column(sa.Column('eliminado', sa.Boolean(), nullable=True))
        batch_op.alter_column('hora',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.drop_column('long')

    #with op.batch_alter_table('Ruta', schema=None) as batch_op:
    #    batch_op.add_column(sa.Column('eliminado', sa.Boolean(), nullable=True))

    with op.batch_alter_table('Tarjeta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('eliminado', sa.Boolean(), nullable=True))

    with op.batch_alter_table('Transaccion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('eliminado', sa.Boolean(), nullable=True))

    #with op.batch_alter_table('Ubicacion', schema=None) as batch_op:
    #    batch_op.add_column(sa.Column('eliminado', sa.Boolean(), nullable=True))

    #with op.batch_alter_table('Ubicacion_usuario', schema=None) as batch_op:
    #    batch_op.add_column(sa.Column('eliminado', sa.Boolean(), nullable=True))

    with op.batch_alter_table('Usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('eliminado', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('id_plan', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'Plan', ['id_plan'], ['id'], ondelete='SET NULL')

    #with op.batch_alter_table('persona_confianza', schema=None) as batch_op:
    #    batch_op.add_column(sa.Column('eliminado', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###
    """
    pass


def downgrade():
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('persona_confianza', schema=None) as batch_op:
        batch_op.drop_column('eliminado')

    with op.batch_alter_table('Usuario', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_plan')
        batch_op.drop_column('eliminado')

    with op.batch_alter_table('Ubicacion_usuario', schema=None) as batch_op:
        batch_op.drop_column('eliminado')

    with op.batch_alter_table('Ubicacion', schema=None) as batch_op:
        batch_op.drop_column('eliminado')

    with op.batch_alter_table('Transaccion', schema=None) as batch_op:
        batch_op.drop_column('eliminado')

    with op.batch_alter_table('Tarjeta', schema=None) as batch_op:
        batch_op.drop_column('eliminado')

    with op.batch_alter_table('Ruta', schema=None) as batch_op:
        batch_op.drop_column('eliminado')

    with op.batch_alter_table('Punto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('long', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.alter_column('hora',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.drop_column('eliminado')
        batch_op.drop_column('lng')

    with op.batch_alter_table('Plan', schema=None) as batch_op:
        batch_op.drop_column('eliminado')

    with op.batch_alter_table('Permiso_usuario', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('eliminado')
        batch_op.drop_column('id_permiso')
        batch_op.drop_column('id_usuario')

    with op.batch_alter_table('Permiso', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_gestor_permiso', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('id_permiso_usuario', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('Permiso_id_permiso_usuario_fkey', 'Permiso_usuario', ['id_permiso_usuario'], ['id'])
        batch_op.create_foreign_key('Permiso_id_gestor_permiso_fkey', 'Usuario', ['id_gestor_permiso'], ['id'])
        batch_op.drop_column('eliminado')

    with op.batch_alter_table('Dispositivo', schema=None) as batch_op:
        batch_op.drop_column('eliminado')
        batch_op.drop_column('cedula')

    with op.batch_alter_table('Caracteristica_Usuario', schema=None) as batch_op:
        batch_op.drop_column('eliminado')

    with op.batch_alter_table('Caracteristica_Plan', schema=None) as batch_op:
        batch_op.drop_column('eliminado')

    with op.batch_alter_table('Caracteristica', schema=None) as batch_op:
        batch_op.drop_column('eliminado')

    # ### end Alembic commands ###
    """
    pass
