"""Agrega columna imagen a Usuario

Revision ID: 406faccc3f06
Revises: 
Create Date: 2025-06-27 15:43:45.301091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '406faccc3f06'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_table('permiso_usuario')
    #op.drop_table('Permiso_Usuario')
    with op.batch_alter_table('Usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagen', sa.String(length=150), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Usuario', schema=None) as batch_op:
        batch_op.drop_column('imagen')

    op.create_table('Permiso_Usuario',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Permiso_Usuario_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('id_dispositivo', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nivel', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_dispositivo'], ['Dispositivo.id'], name='Permiso_Usuario_id_dispositivo_fkey'),
    sa.PrimaryKeyConstraint('id', name='Permiso_Usuario_pkey')
    )
    op.create_table('permiso_usuario',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_dispositivo', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nivel', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_dispositivo'], ['Dispositivo.id'], name='permiso_usuario_id_dispositivo_fkey'),
    sa.PrimaryKeyConstraint('id', name='permiso_usuario_pkey')
    )
    # ### end Alembic commands ###
