"""Migracion resetear tabla

Revision ID: 7575ecc1d280
Revises: 39291912508b
Create Date: 2025-07-09 09:44:03.002604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7575ecc1d280'
down_revision = '39291912508b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaccion_plan')
    with op.batch_alter_table('Permiso_usuario', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('Permiso_usuario_id_usuario_fkey'), type_='foreignkey')
        batch_op.drop_column('id_usuario')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Permiso_usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_usuario', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('Permiso_usuario_id_usuario_fkey'), 'Usuario', ['id_usuario'], ['id'])

    op.create_table('transaccion_plan',
    sa.Column('transaccion_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('plan_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['Plan.id'], name=op.f('transaccion_plan_plan_id_fkey')),
    sa.ForeignKeyConstraint(['transaccion_id'], ['Transaccion.id'], name=op.f('transaccion_plan_transaccion_id_fkey')),
    sa.PrimaryKeyConstraint('transaccion_id', 'plan_id', name=op.f('transaccion_plan_pkey'))
    )
    # ### end Alembic commands ###
