"""Agregar campo eliminado a ruta punto

Revision ID: 9d7305d6925c
Revises: d47d312e3103
Create Date: 2025-07-21 12:06:55.417956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d7305d6925c'
down_revision = 'd47d312e3103'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('RutaPunto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('eliminado', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('RutaPunto', schema=None) as batch_op:
        batch_op.drop_column('eliminado')

    # ### end Alembic commands ###
