"""Modificacion: modificar nombre columnas es_monitor

Revision ID: d1a30b768d14
Revises: 9d7305d6925c
Create Date: 2025-07-24 16:31:46.014372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1a30b768d14'
down_revision = '9d7305d6925c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #with op.batch_alter_table('Usuario', schema=None) as batch_op:
    #    batch_op.add_column(sa.Column('es_monitor', sa.Boolean(), nullable=False))
    #    batch_op.drop_column('es_monitoreo')

    # ### end Alembic commands ###
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #with op.batch_alter_table('Usuario', schema=None) as batch_op:
    #    batch_op.add_column(sa.Column('es_monitoreo', sa.BOOLEAN(), autoincrement=False, nullable=False))
    #    batch_op.drop_column('es_monitor')

    # ### end Alembic commands ###
    pass
