"""Agregar campo modo_perdida

Revision ID: d47d312e3103
Revises: 31dc55a32dbf
Create Date: 2025-07-21 10:44:00.384422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd47d312e3103'
down_revision = '31dc55a32dbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('modo_perdida', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Usuario', schema=None) as batch_op:
        batch_op.drop_column('modo_perdida')

    # ### end Alembic commands ###
